from selenium.webdriver.common.by import By

class PaymentPageLocators:
    PAYMENT_METHOD_TEXT = (By.XPATH, "//p[contains(text(), 'Select a payment method')]")
    INTERNATIONAL_CARD = (By.XPATH, "//span[text()='International Cards']")
    iframe = (By.CLASS_NAME, "wrapper ng-tns-c2801494586-0 ng-star-inserted")
    card = (By.CLASS_NAME, "logo-name ng-star-inserted")
    first_name = (By.ID, "mat-form-field-label-7")
    last_name = (By.ID, "mat-form-field-label-9")
    address = (By.ID, "mat-form-field-label-11")
    city = (By.ID, "mat-form-field-label-15")
    zip = (By.ID, "mat-form-field-label-17")
    state = (By.ID, "mat-form-field-label-19")
    phone = (By.ID, "mat-form-field-label-21")
    card_number = (By.ID, "mat-form-field-label-1")
    exp_date = (By.ID, "mat-form-field-label-3")
    cvv = (By.ID, "mat-form-field-label-5")
    cardholder_name = (By.ID, "mat-form-field-label-13")
    terms_box = (By.ID, "agreeCheckbox")
    pay_now = (By.XPATH, "//button[contains(., 'Pay $')]")
